# Author: Ali Alaqoul <alialaqoul@gmail.com>
"""Assessment report generation — export an AI job to Markdown / HTML / PDF.

Builds a professional report from the agent's session transcript plus the
results store (discovered hosts, services, banners, and variables) and the
engagement metadata supplied by the operator. PDF is produced from the HTML with
xhtml2pdf when available; Markdown and HTML always work with no dependencies.
"""
from __future__ import annotations

import html as _html
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional


@dataclass
class Engagement:
    engagement: str = "Security assessment"
    client: str = ""
    assessor: str = ""
    authorized_by: str = ""
    date: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    target: str = ""
    objective: str = ""

    def rows(self) -> list[tuple[str, str]]:
        return [("Engagement", self.engagement), ("Client", self.client),
                ("Assessor", self.assessor), ("Authorized by", self.authorized_by),
                ("Date", self.date), ("Target", self.target),
                ("Objective", self.objective)]


def build_model(meta: Engagement, transcript: list[dict],
                hosts: dict, facts: dict, final: str) -> dict:
    """Assemble the report data model from raw inputs."""
    actions = [e for e in transcript if e.get("kind") == "tool_result"]
    host_rows = []
    for host, entry in sorted(hosts.items()):
        ports = [p for p in entry.get("ports", {}).values()
                 if p.get("state") == "open"]
        if not ports:
            continue
        host_rows.append({
            "host": host,
            "hostname": entry.get("hostname", ""),
            "ports": sorted(
                ({"port": p["port"], "proto": p.get("proto", "tcp"),
                  "service": p.get("service", ""), "version": p.get("version", "")}
                 for p in ports), key=lambda p: p["port"]),
        })
    return {
        "meta": meta,
        "findings": final or "",
        "hosts": host_rows,
        "facts": facts or {},
        "actions": [{"tool": a.get("name", ""), "args": a.get("args", {}),
                     "ok": a.get("ok", False), "summary": a.get("summary", "")}
                    for a in actions],
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


# ---- Markdown ---------------------------------------------------------------

def to_markdown(m: dict) -> str:
    meta: Engagement = m["meta"]
    out = [f"# {meta.engagement} — Security Assessment Report", ""]
    for k, v in meta.rows():
        if v:
            out.append(f"- **{k}:** {v}")
    out += ["", "## Executive summary / findings", "", m["findings"] or "_None._", ""]

    out += ["## Discovered hosts & services", ""]
    if m["hosts"]:
        for h in m["hosts"]:
            title = h["host"] + (f" ({h['hostname']})" if h["hostname"] else "")
            out += [f"### {title}", "", "| Port | Proto | Service | Version / banner |",
                    "|---|---|---|---|"]
            for p in h["ports"]:
                out.append(f"| {p['port']} | {p['proto']} | {p['service']} | "
                           f"{p['version']} |")
            out.append("")
    else:
        out += ["_No hosts recorded._", ""]

    if m["facts"]:
        out += ["## Discovered information", ""]
        for k, v in m["facts"].items():
            out.append(f"- **{k}:** {v}")
        out.append("")

    out += ["## Actions performed", "", "| Tool | Target | Result |", "|---|---|---|"]
    for a in m["actions"]:
        tgt = a["args"].get("target") or a["args"].get("url") or ""
        out.append(f"| {a['tool']} | {tgt} | "
                   f"{'ok' if a['ok'] else 'no'} — {a['summary'][:80]} |")
    out += ["", f"_Generated by Autopwn on {m['generated']} — for authorized "
            "testing only._"]
    return "\n".join(out)


# ---- HTML -------------------------------------------------------------------

_CSS = """
body{font-family:'Segoe UI',Arial,sans-serif;color:#1a1a1a;margin:40px;line-height:1.5}
h1{color:#0b5394;border-bottom:3px solid #0b5394;padding-bottom:6px}
h2{color:#0b5394;margin-top:28px;border-bottom:1px solid #ccc;padding-bottom:3px}
h3{color:#333;margin-top:18px}
table{border-collapse:collapse;width:100%;margin:8px 0;font-size:12px;table-layout:fixed}
th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;vertical-align:top;word-wrap:break-word;overflow-wrap:break-word}
table.ports th:nth-child(1),table.ports td:nth-child(1){width:9%}
table.ports th:nth-child(2),table.ports td:nth-child(2){width:9%}
table.ports th:nth-child(3),table.ports td:nth-child(3){width:22%}
table.ports th:nth-child(4),table.ports td:nth-child(4){width:60%}
table.acts th:nth-child(1),table.acts td:nth-child(1){width:20%}
table.acts th:nth-child(2),table.acts td:nth-child(2){width:28%}
table.acts th:nth-child(3),table.acts td:nth-child(3){width:52%}
th{background:#0b5394;color:#fff}
tr:nth-child(even){background:#f4f7fb}
.meta td{border:none;padding:2px 8px}.meta th{background:#eee;color:#0b5394;width:150px}
.findings{background:#f7f7f7;border-left:4px solid #0b5394;padding:10px 14px;white-space:pre-wrap;font-size:13px}
.foot{color:#888;font-size:11px;margin-top:30px;border-top:1px solid #ddd;padding-top:8px}
"""


def _esc(s) -> str:
    return _html.escape(str(s or ""))


def to_html(m: dict) -> str:
    meta: Engagement = m["meta"]
    p = [f"<html><head><meta charset='utf-8'><style>{_CSS}</style></head><body>"]
    p.append(f"<h1>{_esc(meta.engagement)} — Security Assessment Report</h1>")
    p.append("<table class='meta'>")
    for k, v in meta.rows():
        if v:
            p.append(f"<tr><th>{_esc(k)}</th><td>{_esc(v)}</td></tr>")
    p.append("</table>")

    p.append("<h2>Executive summary / findings</h2>")
    p.append(f"<div class='findings'>{_esc(m['findings']) or 'None.'}</div>")

    p.append("<h2>Discovered hosts &amp; services</h2>")
    for h in m["hosts"]:
        title = h["host"] + (f" ({h['hostname']})" if h["hostname"] else "")
        p.append(f"<h3>{_esc(title)}</h3><table class='ports'>"
                 "<tr><th>Port</th><th>Proto</th><th>Service</th><th>Version / banner</th></tr>")
        for pt in h["ports"]:
            p.append(f"<tr><td>{pt['port']}</td><td>{_esc(pt['proto'])}</td>"
                     f"<td>{_esc(pt['service'])}</td><td>{_esc(pt['version'])}</td></tr>")
        p.append("</table>")
    if not m["hosts"]:
        p.append("<p><i>No hosts recorded.</i></p>")

    if m["facts"]:
        p.append("<h2>Discovered information</h2><table>"
                 "<tr><th>Variable</th><th>Value</th></tr>")
        for k, v in m["facts"].items():
            p.append(f"<tr><td>{_esc(k)}</td><td>{_esc(v)}</td></tr>")
        p.append("</table>")

    p.append("<h2>Actions performed</h2><table class='acts'>"
             "<tr><th>Tool</th><th>Target</th><th>Result</th></tr>")
    for a in m["actions"]:
        tgt = a["args"].get("target") or a["args"].get("url") or ""
        res = ("ok" if a["ok"] else "no") + " — " + a["summary"][:90]
        p.append(f"<tr><td>{_esc(a['tool'])}</td><td>{_esc(tgt)}</td>"
                 f"<td>{_esc(res)}</td></tr>")
    p.append("</table>")
    p.append(f"<div class='foot'>Generated by Autopwn on {m['generated']} — "
             "for authorized security testing only.</div>")
    p.append("</body></html>")
    return "\n".join(p)


# ---- PDF --------------------------------------------------------------------

def to_pdf(html_str: str, path: Path) -> bool:
    """Render HTML to PDF. Returns True on success (needs xhtml2pdf)."""
    try:
        from xhtml2pdf import pisa
    except Exception:
        return False
    try:
        with open(path, "wb") as f:
            status = pisa.CreatePDF(html_str, dest=f)
        return not status.err
    except Exception:
        return False


def export(m: dict, base: Path, formats: list[str]) -> list[Path]:
    """Write the report in the requested formats. Returns written paths."""
    written: list[Path] = []
    html_str = to_html(m)
    if "md" in formats:
        p = base.with_suffix(".md"); p.write_text(to_markdown(m), encoding="utf-8")
        written.append(p)
    if "html" in formats:
        p = base.with_suffix(".html"); p.write_text(html_str, encoding="utf-8")
        written.append(p)
    if "pdf" in formats:
        p = base.with_suffix(".pdf")
        if to_pdf(html_str, p):
            written.append(p)
    return written
